// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxq5atU-GV6BSUBCDoCvWYmScdIdg33-g',
    appId: '1:902898650256:web:13195a0ce5f833ded29c15',
    messagingSenderId: '902898650256',
    projectId: 'hospital-inventory-a7eea',
    authDomain: 'hospital-inventory-a7eea.firebaseapp.com',
    storageBucket: 'hospital-inventory-a7eea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9f1suYbj6CaWDblokqlKsRTzfaR053ko',
    appId: '1:902898650256:android:e865f3e14c8a124bd29c15',
    messagingSenderId: '902898650256',
    projectId: 'hospital-inventory-a7eea',
    storageBucket: 'hospital-inventory-a7eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnICIxTLeOkf9NOaY4wOmf5XJqR8Nfvw',
    appId: '1:902898650256:ios:c4d55affdcf678d5d29c15',
    messagingSenderId: '902898650256',
    projectId: 'hospital-inventory-a7eea',
    storageBucket: 'hospital-inventory-a7eea.firebasestorage.app',
    iosBundleId: 'com.example.hospitalInventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZnICIxTLeOkf9NOaY4wOmf5XJqR8Nfvw',
    appId: '1:902898650256:ios:c4d55affdcf678d5d29c15',
    messagingSenderId: '902898650256',
    projectId: 'hospital-inventory-a7eea',
    storageBucket: 'hospital-inventory-a7eea.firebasestorage.app',
    iosBundleId: 'com.example.hospitalInventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxq5atU-GV6BSUBCDoCvWYmScdIdg33-g',
    appId: '1:902898650256:web:61d41040441f2c99d29c15',
    messagingSenderId: '902898650256',
    projectId: 'hospital-inventory-a7eea',
    authDomain: 'hospital-inventory-a7eea.firebaseapp.com',
    storageBucket: 'hospital-inventory-a7eea.firebasestorage.app',
  );
}
